language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "rocketeer55-github"
    token:
      secure: "577875fc758ad8a83b0ddf2568ad3338abd5adc3"
jdk:
  - oraclejdk9
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      
